[theme]
primaryColor = "#28a745"  # Green instead of red
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f6f6f6"
textColor = "#2c3e50"
font = "sans serif"

[server]
fileWatcherType = "poll"
maxUploadSize = 10000  # 10 GB limit for data submission uploads
